"""phone number

Revision ID: 667d64b36760
Revises: f25f16febec4
Create Date: 2021-11-06 17:53:07.509299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '667d64b36760'
down_revision = 'f25f16febec4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
